---
title: LDScore - data prep
execute:
  eval: false
#self-contained: true
---


scz_2018.sumstats.gz

- make counter gene lists per celltype input (all remaning genes in sce object)
- the .raw files are annotations with windows for MAGMA, the .sumstat.gz files are for LDscore

LDScore want the full gene list of the celltype and the remaining genes as well

```{r}
here::i_am("04_data_analysis/003_ldscore_analysis/01_data_prep.qmd")
```

# Load packages

```{r}
source(here::here("04_data_analysis/990_code_libraries/02_library-calls-for-renv.R"))
```

# Load data

```{r}
#| eval: true
# read data
sce <- readr::read_rds(here::here("03_data/990_processed_data/001_snrnaseq/07_scflow_analysis/scflow-sce-annotated-highlevel.rds"))
updated_annotations <- readr::read_rds(here::here("03_data/990_processed_data/001_snrnaseq/10_cell_subtypes/subcluster_annotations.rds"))
```

# Data prep

```{r}
# Gene ensembl IDs
gene_ensembl_ids <- data.frame(gene = rownames(sce@assays$RNA@data), ensembl = rownames(sce@assays$RNA@counts))
rownames(sce@assays$RNA@data) <- gene_ensembl_ids$ensembl
```

```{r}
files <- list.files(here::here("03_data/995_ldsc_inputs/01_celltype_markers"), full.names = TRUE)
celltype_markers <- map(files, readr::read_lines)
names(celltype_markers) <- basename(files)

background_genes <- map(celltype_markers, ~ gene_ensembl_ids$ensembl[!gene_ensembl_ids$ensembl %in% .x])

map2(background_genes, names(background_genes), ~ writeLines(.x, here::here("03_data/995_ldsc_inputs/02_backgrounds", paste0("background_genes-", .y))))
```

