
Here is we install/load all the packages we use in this project.

```{r}
#| label: load libraries
#| include: false

## create vector of packages used
pkg <- c("helpers" = c("stringr", "DT", "reshape", "dplyr", "tidyr",
                       "tibble", "purrr", "here", "readr", "kableExtra", 
                       "janitor", "labelled", "BiocManager", "data.table",
                       "gt", "europepmc", "readxl", "NMF", "furrr"),
         "website" = c("downlit", "xml2"),
         "plots" = c("corrgram", "RColorBrewer", "pheatmap", "ggplot2",
                     "ggsci", "cowplot", "scales", "ggvenn", "ggpubr", 
                     "gridExtra", "tidytext", "viridis", "wesanderson",
                     "pals", "ggalluvial"))

pkg_bioconductor <- c("cellity", "scater", "Seurat", "SC3", "DESeq2", "edgeR",
                      "BiocParallel", "org.Hs.eg.db", "pathview", "gage",
                      "gageData", "DropletUtils", "ensembldb", 
                      "AnnotationHub", "patchwork", "scran", "scuttle",  
                      "PCAtools", "batchelor", "bluster", "igraph", 
                      "SingleCellExperiment", "scRNAseq", "biomaRt",
                      "GEOquery", "AnnotationDbi", "clusterProfiler",
                      "DOSE", "enrichplot", "EnsDb.Hsapiens.v79", "fgsea")

# Getting strange behaviour from Seurat - going to try not installing azimuth
# pkg_devtools <- c("sqjin/CellChat", "chris-mcginnis-ucsf/DoubletFinder", 
#                   "satijalab/azimuth")
pkg_devtools <- c("sqjin/CellChat")

## create function to installing any missing packages and then load them all
sort_packages <- function(packages, bioconductor = FALSE, devtools = FALSE) {
    ## Check if packages are not installed and assign the
    ## names of the packages not installed to the variable new.pkg
    new_pkg <- packages[!(packages %in% installed.packages())]
    ## If the packages are bioconductor, install via biocmanager
    ## If there are any packages in the list that aren't installed,
    ## install them
    if (length(new_pkg) & !bioconductor) {
        install.packages(new_pkg, repos = "https://cran.rstudio.com")
    } else if (length(new_pkg) & bioconductor) {
        BiocManager::install(new_pkg)
    } else if (length(new_pkg) & devtools) {
      #devtools::install_github(new_pkg)
      remotes::install_github(new_pkg)
    }
    
    if (devtools) {
      packages <- sapply(strsplit(packages, "/"), tail, n = 1)
    }
    ## load packages
    lapply(packages, require, character.only = TRUE)
}
## use function
sort_packages(pkg)
sort_packages(pkg_bioconductor, bioconductor = TRUE)
sort_packages(pkg_devtools, devtools = TRUE)
```

```{r}
#| purl: false
# subset devtools packages to after the "/" for the library calls
pkg_devtools <- sapply(strsplit(pkg_devtools, "/"), tail, n = 1)
pkg_devtools <- sub("azimuth", "Azimuth", pkg_devtools)

# create library calls for renv
library_calls <- paste0("library(", c(pkg, pkg_bioconductor, pkg_devtools), ")")
write_lines(library_calls, here("04_data_analysis/990_code_libraries/02_library-calls-for-renv.R"))
```

```{r}
rm(pkg, pkg_bioconductor, pkg_devtools, sort_packages)
```