---
title: Subset data for ADDI workshop
execute:
  eval: true
#self-contained: true
---

We want to use some real DRI data as part of the ADDI workshop at the ECR informatics 2024 symposium, but it needs to be small enough to be workable, so I need to subset my data to be less than 1GB 

```{r}
#here::i_am("04_data_analysis/001_snrnaseq_analysis/90_")
```

# Load packages

```{r}
source(here::here("04_data_analysis/990_code_libraries/02_library-calls-for-renv.R"))
```

# Read in data

```{r}
res <- readr::read_rds(here::here("03_data/990_processed_data/001_snrnaseq/08_pseudobulk/pseudobulk_ad-vs-control_deseq2_subtype-annotated.rds")) %>%
  na.omit()

res |> 
  dplyr::slice_sample(n = 10000) |>
  readr::write_csv(here::here("../../reporduciblility/ECR-Informatics-symposium-2024/03_addi_workshop/ad_bbb_pseudobulk.csv"))
```

First we'll read in the scFlow output to a sce

```{r}
#| eval: true
# read data
sce <- readr::read_rds(here::here("03_data/990_processed_data/001_snrnaseq/07_scflow_analysis/scflow-sce-annotated-highlevel.rds"))
```

```{r}
# save gene and ensembl IDs to switch between them as needed
df <- data.frame(gene = rownames(sce@assays$RNA@data), ensembl = rownames(sce@assays$RNA@counts))
df$gene_mix <- ifelse(df$gene == "", df$ensembl, df$gene)
df$gene_mix <- ifelse(duplicated(df$gene_mix), df$ensembl, df$gene_mix)
# make count rownames match data rownames
rownames(sce@assays$RNA@data) <- df$gene_mix
rownames(sce@assays$RNA@counts) <- df$gene_mix
```

Exclude unneeded celltypes

```{r}
sce <- subset(sce, idents = c("Ependymal-donor31", "Astro-donor31"), invert = TRUE)
```

```{r}
sce$highlevel_manual_annotations <- Idents(sce)
```


```{r}
# Step 1: Check the size of your Seurat object
print(object.size(sce), units = "Gb")

# Step 2: Make sure your metadata includes cell type and case/control status
# This step assumes your metadata already has these fields

# Step 3: Calculate proportions
table(Idents(sce), sce$diagnosis)

# Step 4: Decide on a sampling strategy
# For example, if you want to keep 100 cells from each combination of cell type and case/control status

# Step 5: Subset your data
# Define a function to sample cells for each combination of cell type and case/control
sample_cells <- function(celltype, status, n = 100) {
  cells <- WhichCells(sce, idents = celltype, expression = diagnosis == status)
  sample(cells, min(n, length(cells)))
}

# Create a data frame of all combinations of cell type and case/control
combinations <- expand.grid(
  celltype = unique(sce$highlevel_manual_annotations),
  case_control = unique(sce$diagnosis)
)

# Use purrr's map2 to sample cells from each combination
cells_to_keep <- unlist(pmap(
  list(combinations$celltype, combinations$case_control),
  sample_cells
))

# Subset your Seurat object
sce_sub <- subset(sce, cells = cells_to_keep)
# Check ensembl IDs still match
assertthat::assert_that(sum(rownames(sce_sub) != df$gene_mix) == 0)
```

```{r}
# Assuming 'seurat_object' is your Seurat object and 'RNA' is the assay of interest
assay <- GetAssay(sce_sub, assay = "RNA")
feature_names <- rownames(assay@data)

# Create a new data frame for meta.features with the gene names
new_meta_features <- data.frame(row.names = feature_names)
new_meta_features$gene_names <- feature_names

# Assign it back to the assay
assay@meta.features <- new_meta_features

# Replace the assay in the Seurat object
sce_sub[["RNA"]] <- assay
head((sce_sub@assays$RNA@meta.features))
```

```{r}
# Step 6: Check the size of your subset
print(object.size(sce_sub), units = "Gb")

# Step 7: Save the subset
readr::write_rds(sce_sub, here::here("../../reporduciblility/ECR-Informatics-symposium-2024/03_addi_workshop/ad_bbb_seurat_data.rds"))
```

